{% set name = "skglm" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/skglm-{{ version }}.tar.gz
  sha256: 7cd08f2ce99c0b190d8d4daf8137d893f5da2dbaf16aaedcf69a2e3166292d58

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.12
    - numba
    - scipy >=0.18.0
    - scikit-learn >=1.0

test:
  imports:
    - skglm
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://contrib.scikit-learn.org/skglm
  summary: A fast and modular scikit-learn replacement for generalized linear models
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mathurinm
    - Badr-MOUFAD
    - jjerphan
