{% set name = "skglm" %}
{% set version = "0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/skglm-{{ version }}.tar.gz
  sha256: 12d22dc0aef3f76bb43ece16beb7d8ff32b2afd52cba7222d3df3e3ad59661db

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.12
    - numba
    - scipy >=0.18.0
    - scikit-learn >=1.0

test:
  imports:
    - skglm
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://contrib.scikit-learn.org/skglm
  summary: A fast and modular scikit-learn replacement for generalized linear models
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mathurinm
    - Badr-MOUFAD
    - jjerphan
