{% set name = "skglm" %}
{% set version = "0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/skglm-{{ version }}.tar.gz
  sha256: 11037aec119dd2869d6b574b6cca8bae69091eeeefe06cbbd0a5aa879ad79dc7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.12
    - numba
    - scipy >=0.18.0
    - scikit-learn >=1.0

test:
  imports:
    - skglm
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://contrib.scikit-learn.org/skglm
  summary: A fast and modular scikit-learn replacement for generalized linear models
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mathurinm
    - Badr-MOUFAD
    - jjerphan
